"""Two-nudge customer follow-up.

When a customer goes silent mid-conversation, the bot sends one short warm
nudge after CUSTOMER_NUDGE_FIRST_AFTER_HOURS and a second after
CUSTOMER_NUDGE_SECOND_AFTER_HOURS, then stops. Drives by celery beat —
no per-message scheduling, so deploys / restarts can't drop the nudge.

The nudge text is hardcoded (two short, persona-neutral lines) rather than
generated by Claude. Keeps the nudge path cheap, predictable, and impossible
to derail into pushy sales talk. When the customer replies to a nudge the
normal advance_conversation path takes over with full context.
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone
import logging

from sqlalchemy import select

from app.workers.async_runner import run_async
from app.workers.celery_app import celery_app

logger = logging.getLogger(__name__)


NUDGE_MESSAGES = {
    1: "Hi! Abhi tak soch rahe ho? Koi sawaal ho toh batao 😊",
    2: "Yaar ek baar aur check kar raha tha — agar interested ho toh batana, hum yahin hain.",
}

# Per-product conversation states where a nudge would be inappropriate
# (mid-payment, post-payment, manual review, etc.). Pulled from conversation.py.
_NUDGE_BLOCKING_PRODUCT_STATES = {
    "awaiting_payment",
    "verifying",
    "payment_confirmed",
    "failed",
    "manual_review",
    "dispatched_notified",
    "waiting_for_tag",
    "customer_disengaged",
}


def last_customer_message_at(messages: list[dict] | None) -> datetime | None:
    """Walk messages backwards; return the timestamp of the most recent
    customer turn, parsed as a tz-aware datetime. None if no customer turns."""
    if not messages:
        return None
    for entry in reversed(messages):
        if (entry.get("role") or "") != "customer":
            continue
        ts = entry.get("timestamp")
        if not ts:
            continue
        try:
            parsed = datetime.fromisoformat(ts)
        except (TypeError, ValueError):
            continue
        if parsed.tzinfo is None:
            parsed = parsed.replace(tzinfo=timezone.utc)
        return parsed
    return None


def last_message_role(messages: list[dict] | None) -> str | None:
    if not messages:
        return None
    return (messages[-1].get("role") or "") or None


def should_nudge_now(
    messages: list[dict] | None,
    nudge_state: dict | None,
    first_after_hours: int,
    second_after_hours: int,
    now: datetime | None = None,
) -> int:
    """Return target nudge count (1 or 2) if a nudge should fire now, else 0.

    Pure function. Logic:
      - Last message must be from the customer (we don't nudge after a bot or
        seller_manual turn).
      - Customer message age must exceed the threshold for the next nudge.
      - Already-sent nudges (nudge_state.count) suppress lower-numbered targets.
      - Two nudges max — count >= 2 means we're done.
    """
    last_msg_at = last_customer_message_at(messages)
    if last_msg_at is None:
        return 0
    if last_message_role(messages) != "customer":
        return 0

    state = nudge_state or {}
    current_count = int(state.get("count", 0) or 0)
    if current_count >= 2:
        return 0

    current = now or datetime.now(timezone.utc)
    elapsed_h = (current - last_msg_at).total_seconds() / 3600.0

    if current_count == 0 and elapsed_h >= first_after_hours:
        return 1
    if current_count == 1 and elapsed_h >= second_after_hours:
        return 2
    return 0


@celery_app.task(name="app.workers.nudge.scan_for_nudge_candidates")
def scan_for_nudge_candidates() -> None:
    run_async(_scan_for_nudge_candidates())


async def _scan_for_nudge_candidates() -> None:
    from app.models.conversation import Conversation
    from app.database import worker_session
    from app.config import settings as _settings

    async with worker_session() as db:
        # Only nudge threads currently mid-funnel (a product is in focus).
        # Idle post-purchase threads (product_id NULL) are never nudged.
        result = await db.execute(
            select(Conversation.id, Conversation.messages, Conversation.nudge_state).where(
                Conversation.product_id.isnot(None),
            )
        )
        candidates: list[tuple[str, int]] = []
        for cid, messages, nudge_state in result.all():
            target = should_nudge_now(
                messages,
                nudge_state,
                _settings.CUSTOMER_NUDGE_FIRST_AFTER_HOURS,
                _settings.CUSTOMER_NUDGE_SECOND_AFTER_HOURS,
            )
            if target:
                candidates.append((str(cid), target))

    if not candidates:
        return

    logger.info(
        "scan_for_nudge_candidates: dispatching %d nudge(s)",
        len(candidates),
    )
    for cid, target in candidates:
        send_nudge.apply_async(args=[cid, target])


@celery_app.task(name="app.workers.nudge.send_nudge")
def send_nudge(conversation_id: str, target_count: int) -> None:
    run_async(_send_nudge(conversation_id, target_count))


async def _send_nudge(conversation_id: str, target_count: int) -> None:
    from app.models.conversation import Conversation
    from app.models.conversation_product import ConversationProduct
    from app.models.seller import Seller
    from app.database import worker_session
    from app.config import settings as _settings
    from app.integrations.instagram import InstagramClient

    if target_count not in NUDGE_MESSAGES:
        logger.warning("send_nudge: invalid target_count=%s", target_count)
        return

    async with worker_session() as db:
        result = await db.execute(select(Conversation).where(Conversation.id == conversation_id))
        conversation = result.scalar_one_or_none()
        if not conversation:
            return
        # Only nudge a thread still in focus (mid-funnel).
        if not conversation.product_id:
            return

        # Re-check eligibility now (the scan and this task race a bit).
        target_now = should_nudge_now(
            conversation.messages,
            conversation.nudge_state,
            _settings.CUSTOMER_NUDGE_FIRST_AFTER_HOURS,
            _settings.CUSTOMER_NUDGE_SECOND_AFTER_HOURS,
        )
        if target_now != target_count:
            logger.info(
                "send_nudge %s: target shifted (%s → %s) — skipping",
                conversation_id, target_count, target_now,
            )
            return

        # Don't nudge mid-payment / mid-review / waiting_for_tag.
        if conversation.product_id:
            cp_result = await db.execute(
                select(ConversationProduct).where(
                    ConversationProduct.conversation_id == conversation.id,
                    ConversationProduct.product_id == conversation.product_id,
                ).order_by(ConversationProduct.created_at.desc()).limit(1)
            )
            cp = cp_result.scalars().first()
            if cp and cp.state in _NUDGE_BLOCKING_PRODUCT_STATES:
                logger.info(
                    "send_nudge %s: blocked by conv_product state=%s",
                    conversation_id, cp.state,
                )
                return

        seller_result = await db.execute(select(Seller).where(Seller.id == conversation.seller_id))
        seller = seller_result.scalar_one_or_none()
        if not seller or not seller.is_active or not seller.instagram_token:
            logger.info("send_nudge %s: seller inactive or unauthorised", conversation_id)
            return

        nudge_text = NUDGE_MESSAGES[target_count]

        try:
            client = InstagramClient(seller.instagram_token, seller.fb_page_id)
            result = await client.send_message(conversation.customer_instagram_id, nudge_text)
            mid = result.get("message_id") if isinstance(result, dict) else None
        except Exception as exc:
            logger.error("send_nudge %s: IG send failed: %s — leaving state untouched", conversation_id, exc)
            return

        # Append the nudge as a bot turn so subsequent customer replies have
        # full context and the disengagement-detection layer (Feature 3) can
        # correctly recognise an "ok bye" response.
        msgs = list(conversation.messages or [])
        entry: dict = {
            "role": "bot",
            "content": nudge_text,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "nudge_count": target_count,
        }
        if mid:
            entry["mid"] = mid
        msgs.append(entry)
        conversation.messages = msgs
        conversation.nudge_state = {
            "count": target_count,
            "last_nudged_at": datetime.now(timezone.utc).isoformat(),
        }
        await db.commit()

        logger.info(
            "send_nudge %s: sent nudge #%d (text=%r)",
            conversation_id, target_count, nudge_text,
        )
